/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // A plain section label above the intro doc, matching the uppercase headings
    // the Guides / Security bulletins / Config reference categories render as.
    // `html` rather than a category so it stays a label: no link, no caret, no
    // collapse. Styled by .dn-sidebar-label in src/css/components.css.
    {
      type: 'html',
      value: 'Get started',
      className: 'dn-sidebar-label',
      defaultStyle: false,
    },
    { type: 'autogenerated', dirName: '.' },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
